### ISSUE TITLE
Implement Surveys for Courses

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1020]
To do Surveys. Related issues include:
#110 - Allow optional questions
#147 - Response summary should show results by response, and by question

##### Roadmap

Feature Release
- [x] Basic survey creation, submission and report
    - [x] [5] Implement basic Survey Sections
    - [x] [3] Write basic frontend tests for each page
    - [x] [5] Allow questions to be re-ordered
    - [x] [3] Responses index page for teachers to see who has (not) responded
    - [x] [1] Do staff view of Show Response page
- [x] Email Notifications
    - [x] [1] Send reminder when survey opens
    - [x] [1] Send reminder when survey is about to close
    - [x] [3] Manually send emails to those who have not submitted.
- [x] [1] Implement "allow edit after submit" feature - staff expects no changes after all submitted before expire date.
- [x] [3] Implement Anonymous switch
    - [x] Update results page
    - [x] Update responses index page, and permissions for responses show page
- [x] [3] Allow un-submit from response index page (all cases) and response show (only if not anonymous)
- [x] [1] Publish sidebar / Course::Component-ize
- [x] [3] Allow sections to be re-ordered
- [x] [5] Duplication
- [ ] CSV downloading
- [ ] Write factories and tests - factories, controller, frontend/integration
- [ ] Performance optimization

Prepare for 200pax Runes Contest
- [x] [1] Show number of responses on result / response page
- [ ] Async uploading of Images (It times out now)
- [x] ~Switch to split form by sections (to avoid 1000 images per page)~ From 2017 runes contests, this might be unnecessary complexity.

**Comment by benleong** [comment]
@weiqingtoh Pls also support imagines to support the CS1010S Runes Contest. :-P

**Comment by luoyanjie** [comment]
finish sections: 5 for sprint on 7 March
list users:  3
Un-submit or let users edit response?  think through

**Comment by kxmbrian** [comment]
Completed with the following PRs:
#2255 #2247 #2244 #2242 #2240 #2237 #2229 #2228 #2220 #2206 #2201 #2196 #2195 #2193 #2189 #2183 #2162 #2141 #2136 #2117 #2115 #2101 #2093 #2074 #2065 #2060 #2059 #2044 #2026 #2000 #1992 #1987 #1986 #1980 #1968 #1954 #1917

Remaining items are split into the following PRs:
#2256 #2257 #2258
