### ISSUE TITLE
Implement Videos Component

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1893]
Adding this here for record purposes: 

- [x] Migration + base models (#1780)
- [x] Todo helpers and transitions (#1780)
- [x] Notifiers for opening and closing video (#1780)
- [x] Base controllers (#1844)
- [x] Implementing component, sidebar, settings (#1844)
- [x] Videos listing page (#1844)
- [x] Video permissions (#1844)
- [ ] Video submission permissions
- [ ] Summary of video submissions
- [ ] Attempt video submission page (youtube for now)
- [ ] Implement lesson_plan_item for video type objects
