### ISSUE TITLE
Upgrade to Rails 5.0

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2271]
Since Rails 5.1 is coming out soon, support for Rails 4.2 will be stopped soon. To upgrade. 

#### Dependencies
- [x] Remove codebase depenedence on `squeel`, swap out to `baby_squeel` #2283
- [x] Figure out an alternative for `cancancan-squeel` [cancancan-baby_squeel](https://github.com/jeremyyap/cancancan-baby_squeel)
- [x] Remove both `squeel` and `cancancan-squeel` #2517
- [x] Upgrade `devise` #2513 
- [x] Upgrade `activerecord-userstamp` lowjoel/activerecord-userstamp@8b0a51a
    **Gem is not fully Rails 5 compatible.**
    - lowjoel/activerecord-userstamp#27
    - Temporary fix implemented in #2530 breaks on Rails 5
    - [Rails issue](https://github.com/rails/rails/issues/25379)
    - [Someone else forked and implemented a fix](https://github.com/paneer-tikka/activerecord-userstamp)
- [x] Upgrade `schema_plus` SchemaPlus/schema_plus#229
- [x] Remove or replace `rails_dev_boost` thedarkone/rails-dev-boost#61
- [x] Update Rails dependencies for the following gems:
    - [x] `active_record-acts_as` [Github](https://github.com/Coursemology/active_record-acts_as)
    - [x] `simple_form-bootstrap` [Github](https://github.com/lowjoel/simple_form-bootstrap)
    - [x] `coursemology-polyglot` [Github](https://github.com/Coursemology/polyglot)

#### Rails 5 breaking changes

- [x] `ActiveRecord::Associations::Preloader` is expected to return `ActiveRecord::Relation` which responds to `load` rails/rails@caa178c
- [x] `ActiveJob::QueueAdapters::InlineAdapter` methods are no longer singletons rails/rails#19295
- [x] Pass `formats` to `lookup_context` rails/rails@face604
- [x] `ActiveRecord::Associations::Builder::HasMany.valid_options` changed to class method rails/rails@b83f364
- [x] `ActiveRecord::FinderMethods.find_nth` changed to private method rails/rails@5b14129
- [x] ActiveRecord errors - `active_record-acts_as`

```
> Course.first.assessments.first
NoMethodError: undefined method `_reflect_on_association' for nil:NilClass

> Course::Assessment.first.programming_questions.first
NoMethodError: undefined method `_reflect_on_association' for nil:NilClass
```

Suspect `has_many through:` to be broken due to `active_record-acts_as` gem being incompatible with Rails 5. The above queries work after switching to the official gem release.

- [x]  Mailer errors -> [ActionMailer Change Log](https://github.com/rails/rails/blob/5-0-stable/actionmailer/CHANGELOG.md#rails-500-june-30-2016)
 
```
RuntimeError:
    You've accessed the message before asking to deliver it later,
    so you may have made local changes that would be silently lost if we enqueued a job to deliver it.
    Why? Only the mailer method *arguments* are passed with the delivery job!
    Do not access the message in any way if you mean to deliver it later.

Workarounds:
    1. don't touch the message before calling #deliver_later,
    2. only touch the message *within your mailer method*, or
    3. use a custom Active Job instead of #deliver_later.
```

**Comment by benleong** [comment]
Yeah, we should do an upgrade to Rails 5 soon.

Thanks!

-Ben

**Comment by jeremyyap** [comment]
Closed by #2584 :tada:
