### ISSUE TITLE
New CourseUser role for auditing staff

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2910]
There are use cases where courses owners invites course staff that for auditing or sharing purposes. Most of the time they are an observer, where they can see what other course staff can see (Eg. see the assessment content, questions and submissions), but not participate in them (student level permissions). 

Currently the workaround is to declare them as phantom staff, but it doesn't solve the problem of having staff accidentally modifying course content. The approach to solving this is to introduce a new course user role (eg. `staff_observer`) that has a mix of student and staff abilities. These are the high level principles/objectives for the `staff_observer`:
  - Able to do everything a student can do. 
  - Able to view all content as a staff, but not make any modifications.
  - Able to view all unpublished or hidden or locked items.
  - Able to attempt assessments and have both a staff and student view. 
  - Able to duplicate content from course to own courses.

This will support the ability for course owners to share their teaching/learning practices with more confidence (that observers are not able to change their settings).

---

### Tasks and Observer's Functions
Since there are many things to correct, this is the list for me to track, and for team discussion. 

#### Front-end Tasks for New Role
 - [ ] Support role upgrade to staff (from student) (#)
 - [ ] Support role in user invitation (#)
 - [ ] Scrub assessment to ensure no issues (#)
    - [x] Check submissions view of others students (Done for all states) (Includes viewing past answers)
    - [x] Check access on access logs
 - [ ] Fix surveys to ensure no issues (#)
    - [x] Check attempt survey and submit response
    - [x] Check access on results and responses

#### Changes to Permissions
- [x] Achievements (#2939)
  - Able to see all draft and published achievements as well as icons.
  - Not able to modify or delete achievements.
- [x] Announcements (#2939)
  - Able to see all draft and published announcements, but not able to modify.
- [x] Conditions (#2939)
  - Unable to modify conditions
- [x] Course (#2939)
  - Unable to manage course
- [x] Discussion (#2939)
  - Able to see what a student can see, but unable to modify/manage any discussions
  - Comments sidebar brings observer to view all comments.
- [x] Duplication (#2939)
  - Able to `duplicate_from` Course, but not `duplicate_to`.
- [x] Experience Points Record and Disbursement (#2910)
  - Can view own records, and cannot disburse experience points
- [x] Forums (#2939)
  -  Can see all topics (including hidden ones), but cannot manage / moderate / modify. 
- [x] Groups (#2939)
  - Can see all groups but cannot modify.
- [x] Lesson Plan (#2939)
  - Can see all published and unpublished lesson plan items.
- [x] Virtual Classrooms (#2939)
  - Cannot manage virtual classroom, but can access recorded videos.
- [x] ~~Statistics~~
  -  Can see all course statistics => **No action required**
- [x] Levels (#2947)
  -  Can see but cannot edit levels.
- [x] Materials (#2947)
  - Can see all folders and download but cannot modify any information.
- [x] Surveys (#2947)
  - Can see all published and unpublished surveys, and responses of students.
  - Additional (#)
    - Extra permissions to support attempting of surveys for observers. 
- [x] Videos (#2947)
  -  Can see all published and unpublished videos, and student submissions. 
  - Cannot modify or update videos or submissions.
- [x] Assessments (#2947)
  - Able to view all assessments, questions (and correct answers), submissions
  - Able to attempt their own assessment 
  - Additional (#)
    - Attempting Submissions: Observer will know which student has attempted but not be able to view the submission and answers.
    - All other Submission States: Observer can only see and view answers of submitted submissions but cannot do anything except comment. 
    - Cannot view Access Logs for password protected assessments.
