### ISSUE TITLE
Video submissions by staff should not be cached

### ISSUE THREAD

**Issue by trangmei** [Coursemology/coursemology2#3310]
Currently when staff views a video, an empty submission is created (without any session and event).
Once a submission is created, a statistic record is created. But without session and event data, the statistic is zero. This skews the aggregated statistics to the left (lower percent watched, higher view count).

#TODO:
- [ ] Change in application code to not cache course staff's video submissions; and
- [ ] once-off job/migration to remove video submissions statistics for course staff and recompute impacted video statistics; and
- [ ] Filter to only get course students' video submissions to display correct video submission count.
