### ISSUE TITLE
Allow change of Videos URL

### ISSUE THREAD

**Issue by trangmei** [Coursemology/coursemology2#3312]
Currently changing video URL is not allowed once there are associative submissions (and sessions and events).

Prof requested to allow changing of URL at all times, with a warning message.

#TODO:
Upon changing of Video URL:
- [ ] Popup warning to user
- [ ] Destroy all associative submissions, sessions, events, statistics
- [ ] Set video duration to 0
- [ ] Change URL and save video

**Comment by fonglh** [comment]
Essentially, reverse the design decision made in #2932.
