### ISSUE TITLE
Groups Phase 2

### ISSUE THREAD

**Issue by zhuhanming** [Coursemology/coursemology2#4401]
Issue created more for internal bookkeeping, based on comments from #4299.

## TODO List

- [x] There are a few type errors when editing a specific group: Warning: Failed prop type: The prop `students[0].groupUserId` is marked as required in `GroupUserManagerList`, but its value is `undefined`., Warning: Failed prop type: The prop `user.groupUserId` is marked as required in `GroupUserManagerListItem`, but its value is `undefined`. Warning: Failed prop type: The prop `staff[0].groupUserId` is marked as required in `GroupUserManagerList`, but its value is `undefined`.
- [x] Add phantom user indicator
- [x] Add ability to click edit group in main view and straight away go to editing the group in the group manager view.
- [x] In the 'users that can be added/users in group' list, I think it would be nice to indicate if a user is already in another group (maybe can indicate which other group).
- [x] Disable students from being upgraded from Member to Manager
- [x] Disallow students and observers to edit group
- [x] Add phantom user indicator in the group edit page
- [x] Add checkbox to filter out the phantom user
- [x] Change the phantom icon into the more intuitive one (ghost logo will be provided by @purfectliterature )

- [ ] `Add more tests` (not important for now)

- [ ]  `think there will be a performance issue (in prod) when adding/removing students in manage groups, everytime a student is added/removed, the whole lists are re-rendered (see below - the spikes on top right happen when a student is added/removed). To add in todo: prevent rerender of the whole lists.` (not important for now)
- [ ] `Add CSV upload functionalities.` (will be pulled back into one separate issue)

**Comment by ekowidianto** [comment]
@bivanalhar When you are done with your current issue, you can start working on this. I have sorted the TODO tasks from the simplest to the most complex one and I think you can follow the sequence.
