### ISSUE TITLE
Apply devise confirmable to emails

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#594]
In emails management:

### Tasks
- [x] Get devise confirmable/recoverable to work with multiple emails
- [x] Use image/text to indicate the verification status
- [x]  Button to resend verification email
- [x] Abilities

**Comment by allenwq** [comment]
Searched around, think devise confirmable does not work well for multiple emails.

I think we will need to manually define our confirmation logic and use a different confirmation token for each email. 

@lowjoel What do you think ?

**Comment by lowjoel** [comment]
@allenwq what's the status of this now?

**Comment by allenwq** [comment]
@lowjoel The UI for resending confirmation email and showing confirmation
status haven't finished yet.
